# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2806ed8ed739bf337e888ea4f6dcf704f4369f6fba354552e808e929187e308e17eab2c1253b9e9a8d86bd3180281f5bdd0bdec8dff60c250e502f1eb5e1f061

test:
  secret_key_base: 2f1d1e3355fdf5344aff5dcaa76cb2c0c951a125a2780355522a2881709e07d9d3f1ab3b1670fac2bb1d25516de4181fd06dbee5d43d8a238d863224dae2d585

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
